[project]
name = "redis-mcp-server"
version = "0.2.0-alpha"
description = "Redis MCP Server, by Redis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.5.0",
    "redis>=6.0.0",
    "python-dotenv>=0.9.9",
    "numpy>=2.2.4",
]

[project.scripts]
mcp-redis = "src.main:main"